# Generated by Django 4.1.1 on 2022-10-09 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategorijas', 'verbose_name_plural': 'Kategorijos'},
        ),
        migrations.AlterModelOptions(
            name='inscription',
            options={'verbose_name': 'Užrašas', 'verbose_name_plural': 'Užrašai'},
        ),
    ]
