# Generated by Django 4.1.1 on 2022-10-09 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_alter_category_options_alter_inscription_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategorija', 'verbose_name_plural': 'Kategorijos'},
        ),
    ]
