# Generated by Django 4.1.1 on 2022-10-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_category_reader_inscription_reader'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='image',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='Nuotrauka'),
        ),
    ]
